import { artUrl, type Art, type Pal } from './px'

// ============================================================
// モンスターの ドット絵
// ・ザコは 24×24ドット、大ボスは 32×32ドット（フィールドでも 戦闘でも おなじ絵）
// ・左右対称の モンスターは「左半分」だけ かいて sym() で 鏡にする。
//   → 手で かく量が 半分になり、左右の ズレも おきない。
// パレットの文字： A=本体 B=かげ／おなか C=つの・くちばし など D=りんかく
//                 E=白目 P=くろ目 W=きば・光
// ============================================================

// 左半分を 鏡にして 全体にする（12→24 / 16→32）
const sym = (half: Art): Art => half.map((r) => r + [...r].reverse().join(''))

// ---------------- ザコ（左12ドット → 24×24） ----------------

const SLIME = sym([
  '............',
  '............',
  '............',
  '..........DD',
  '.........DAA',
  '........DAAA',
  '.......DAAAA',
  '......DAAAAA',
  '.....DAAAAAA',
  '....DAAAAAAA',
  '...DAWWAAAAA',
  '..DAWWWAAAAA',
  '..DAAWAAAAAA',
  '..DAAAAEEEAA',
  '..DAAAAEPPAA',
  '..DAAAAEPPAA',
  '..DAAAAEEEAA',
  '..DAAAAAAAAA',
  '..DAAAAAADDD',
  '..DAAAAAADWW',
  '..DAAAAAAAAA',
  '...DAAAAAAAA',
  '....DDAAAAAA',
  '......DDDDDD',
])

const BUG = sym([
  '............',
  '............',
  '.......C....',
  '........C...',
  '.........C..',
  '.........DDD',
  '........DAAA',
  '.......DAAAA',
  '.......DAEEE',
  '.......DAEPP',
  '.......DAAAA',
  '.......DAAWW',
  '.......DAAAA',
  '......DDDDDD',
  '.....DBAAAAA',
  '.....DBAAAAA',
  '....DDDDDDDD',
  '....DBAAAAAA',
  '....DBAAAAAA',
  '....DDDDDDDD',
  '.....DBAAAAA',
  '.....DDAAAAA',
  '......DDDDDD',
  '............',
])

const BAT = sym([
  '............',
  'DD..........',
  'DBD.........',
  'DBBD........',
  'DBBBD.......',
  'DBCBBD..DDDD',
  'DBCBBBD.DAAA',
  'DBCBBBBDDAEE',
  'DBCBBBBBDAEP',
  '.DBBBBBBDAAA',
  '..DBBBBBDAWW',
  '...DBBBBDAAA',
  '....DBBBDAAA',
  '.....DBBDAAA',
  '......DBDDAA',
  '.......DDDAA',
  '.........DAA',
  '.........DDD',
  '............',
  '............',
  '............',
  '............',
  '............',
  '............',
])

const BEAST = sym([
  '............',
  '..DD........',
  '..DAD.......',
  '..DAAD......',
  '..DAAAD.....',
  '..DAAAADDDDD',
  '..DAAAAAAAAA',
  '..DAEEEAAAAA',
  '..DAEPPAAAAA',
  '..DAAAAAAAAA',
  '...DAAAAABBB',
  '....DAAAABBB',
  '.....DAAABWW',
  '.....DAAAAAA',
  '....DAAAAAAA',
  '...DAAAAAAAA',
  '..DAAAAAAAAA',
  '..DAAAAAAAAA',
  '..DAAAAAAAAA',
  '..DAADDAAAAA',
  '..DAAD.DAAAA',
  '..DAAD.DAAAA',
  '..DDDD.DDDDD',
  '............',
])

const GHOST = sym([
  '............',
  '............',
  '......DDDDDD',
  '....DDAAAAAA',
  '...DAAAAAAAA',
  '..DAAAAAAAAA',
  '..DAAAAAAAAA',
  '..DAEEEAAAAA',
  '..DAEPPAAAAA',
  '..DAEEEAAAAA',
  '..DAAAAAAAAA',
  '..DAAAAAAAAA',
  '..DAAAAAADDD',
  '..DAAAAAADWW',
  '..DAAAAAADDD',
  '..DAAAAAAAAA',
  '..DAAAAAAAAA',
  '..DAAAAAAAAA',
  '..DAAAAAAAAA',
  '..DAADDDAAAA',
  '..DAD...DAAA',
  '..DD.....DAA',
  '.........DDD',
  '............',
])

const ROBOT = sym([
  '.......C....',
  '.......C....',
  '......DDDDDD',
  '.....DAAAAAA',
  '.....DAEEEAA',
  '.....DAEPPAA',
  '.....DAAAAAA',
  '.....DACCCCC',
  '.....DAAAAAA',
  '...DDDDDDDDD',
  '..DBDAAAAAAA',
  '..DBDABBBBBB',
  '..DBDABBBBBB',
  '..DBDAAAAAAA',
  '..DBDAAAAAAA',
  '..DDDDDDDDDD',
  '.....DAAD...',
  '.....DAAD...',
  '.....DAAD...',
  '.....DDDD...',
  '............',
  '............',
  '............',
  '............',
])

const CRAB = sym([
  '............',
  '.DD.........',
  'DAAD........',
  'DAAAD.......',
  'DAAAD...DDDD',
  '.DAAD..DAAAA',
  '..DDD.DAAAAA',
  '.....DAEEEAA',
  '.....DAEPPAA',
  '.....DAAAAAA',
  '....DAAAAAAA',
  '....DABBBBBB',
  '....DABBBBBB',
  '....DAAAAAAA',
  '....DDDDDDDD',
  '..DD.DD.DD..',
  '.DD..DD..DD.',
  '............',
  '............',
  '............',
  '............',
  '............',
  '............',
  '............',
])

const TURTLE = sym([
  '............',
  '............',
  '............',
  '.........DDD',
  '........DAAA',
  '........DAEE',
  '........DAAA',
  '....DDDDDDDD',
  '..DDBBBBBBBB',
  '.DBBCCCCCCCC',
  'DBBCCCCCCCCC',
  'DBCCCCAACCCC',
  'DBCCCCAACCCC',
  'DBBCCCCCCCCC',
  '.DBBCCCCCCCC',
  '..DBBBBBBBBB',
  '...DDDDDDDDD',
  '....DAAD.DAA',
  '....DAAD.DAA',
  '....DDDD.DDD',
  '............',
  '............',
  '............',
  '............',
])

const MAGE = sym([
  '...........C',
  '..........CC',
  '.........DCC',
  '........DCCC',
  '.......DCCCC',
  '......DCCCCC',
  '.....DCCCCCC',
  '..DDDDDDDDDD',
  '.....DAAAAAA',
  '.....DAEEEAA',
  '.....DAEPPAA',
  '.....DAAAAAA',
  '....DBBBBBBB',
  '...DBBBBBBBB',
  '..DBBBBBBBBB',
  '..DBBBAAABBB',
  '..DBBBBBBBBB',
  '..DBBBBBBBBB',
  '..DBBBBBBBBB',
  '..DBBBBBBBBB',
  '...DBBBBBBBB',
  '....DDDDDDDD',
  '............',
  '............',
])

// ---- 左右ひたいちでない ザコ（24幅を そのまま かく） ----

const BIRD: Art = [
  '........................',
  '........................',
  '..........DDDD..........',
  '.........DAAAAD.........',
  '........DAEPAAAD........',
  '........DAAAAAADCC......',
  '........DAAAAAADCC......',
  '.......DAAAAAAAD........',
  '......DAABBBBAAD........',
  '.....DAAABBBBAAAD.......',
  '....DAABBBBBBBBAAD......',
  '....DAABBBBBBBBAAD......',
  '....DAAABBBBBBAAAD......',
  '.....DAAAABBAAAAD.......',
  '......DAAAAAAAAD........',
  '.......DAAAAAAD.........',
  '........DAAAAD..........',
  '.........DAAD...........',
  '........DCDDCD..........',
  '........DC..CD..........',
  '.......DDD..DDD.........',
  '........................',
  '........................',
  '........................',
]

const FISH: Art = [
  '........................',
  '........................',
  '........................',
  '..........DDDDD.........',
  '.......DDDAAAAADD.....DD',
  '.....DDAAAAAAAAAAD...DAD',
  '...DDAAAAAAAAAAAAAD.DAAD',
  '..DAAEEAAAAAAAAAAAADAAAD',
  '..DAEPPAAAAAAAAAAAAAAAAD',
  '.DAAEEAAAACCCAAAAAAAAAAD',
  '.DAAAAAAAACCCAAAAAAAAAAD',
  '.DAAWWAAAAAAAAAAAAAAAAAD',
  '..DAAAAAAAAAAAAAAAAAAAAD',
  '..DBBBBBBBBBBBBBBBBBBAAD',
  '...DDBBBBBBBBBBBBBBDDAAD',
  '.....DDBBBBBBBBBDD...DAD',
  '.......DDDDDDDDD......DD',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
]

const SNAKE: Art = [
  '........................',
  '........................',
  '.............DDDDD......',
  '............DAAAAAD.....',
  '............DAEPAAD.....',
  '............DAAAAAD.....',
  '............DAAWWD..CC..',
  '............DAAAD...CC..',
  '...........DAAAAD.......',
  '..........DAAAAD........',
  '.........DAAAAD.........',
  '........DAAAAD..........',
  '.......DAAAAD...........',
  '......DAAAAD............',
  '.....DAAAAD.............',
  '....DAAAAAADDDDDD.......',
  '..DDAAAAAAAAAAAAAAD.....',
  '..DAABBBBBBBBBBBBAD.....',
  '..DAABBBBBBBBBBBBAD.....',
  '..DAAAAAAAAAAAAAAAD.....',
  '...DDDDDDDDDDDDDDD......',
  '........................',
  '........................',
  '........................',
]

// ---------------- 大ボス（左16ドット → 32×32） ----------------

// ドラゴンは よこむき（プロフィール）で えがく。
// 左に のびた 長い口先＋あけた アゴ＋うしろに そったツノ＋
// S字の 首＋つばさ＋うろこの おなか＋しっぽ＋かぎづめの あし。
// ※正面むきだと「目と口のある まるい顔」に なってしまい、
//   カエルや ゴブリンに 見えてしまうため よこむきに した。
const B_DRAGON: Art = [
  '................................',
  '................................',
  '....................CC..........',
  '...................CC...........',
  '..................CC............',
  '.................CC..........DD.',
  '.........DDDDDDDDC..........DBD.',
  '.......DAAAAAAAAAAD........DBBD.',
  '.....DAAAAAEEEAAAAD.......DBBBD.',
  '...DAAAAAAAEPPAAAAD......DBCBBD.',
  '..DAAAAAAAAAAAAAAAD.....DBCBBBD.',
  '..DWWWWWWWWWWAAAAD.....DBCBBBBD.',
  '...DDDDDDDDDDDAAAD....DBCBBBBBD.',
  '....DWWWWWWWWWDAAAD..DBCBBBBBBD.',
  '.....DAAAAAAAADAAAD..DBBCBBBBBD.',
  '.......DDDDDDDDAAAD.DBBCBBBBBBD.',
  '.............DAAAAADDBBBCBBBBBD.',
  '.............DAAAAAADDBBBBBBBD..',
  '............DAAAAAAAADDBBBBD....',
  '...........DAAAAAAAAAAAAD.......',
  '..........DAAAAAAAAAAAAAAD......',
  '..........DABBBBBBBBBBBBAD......',
  '..........DABBBBBBBBBBBBADDAAD..',
  '..........DABBBBBBBBBBBBADDAAAD.',
  '...........DABBBBBBBBBBADDAAAAD.',
  '...........DAAAAAAAAAAADDAAAD...',
  '...........DAAAAAAAAAAADDDD.....',
  '...........DDDDDDDDDDDDD........',
  '............DAAD...DAAD.........',
  '............DAAD...DAAD.........',
  '...........DCAACD.DCAACD........',
  '...........DDDDDD.DDDDDD........',
]

const B_KING = sym([
  '................',
  '................',
  '........C..C...C',
  '........CCCCCCCC',
  '.......DCCCCCCCC',
  '.......DDDDDDDDD',
  '........DAAAAAAA',
  '........DAEEEAAA',
  '........DAEPPAAA',
  '........DAEEEAAA',
  '........DAAAAAAA',
  '........DAAWWWWW',
  '.........DAAAAAA',
  '.........DWWWWWW',
  '..........DWWWWW',
  '.....DDDDDDDDDDD',
  '....DBBBBBBBBBBB',
  '...DBBBBBBBBBBBB',
  '..DBBBBBCCCCCCCC',
  '..DBBBBBCCCCCCCC',
  '..DBBBBBBCCCCCCC',
  '..DBBBBBBBBBBBBB',
  '..DBBBBBBBBBBBBB',
  '..DBBBBBBBBBBBBB',
  '..DBBBBBBBBBBBBB',
  '..DBBBBBBBBBBBBB',
  '...DBBBBBBBBBBBB',
  '....DBBBBBBBBBBB',
  '.....DDBBBBBBBBB',
  '.......DDDDDDDDD',
  '................',
  '................',
])

const B_DEMON = sym([
  '................',
  'C...............',
  'CC..............',
  '.CC.............',
  '..CC............',
  '...CC...........',
  '....CCDDDDDDDDDD',
  '.....DAAAAAAAAAA',
  '.....DAAEEEAAAAA',
  '.....DAAEPPAAAAA',
  '.....DAAEEEAAAAA',
  '.....DAAAAAAAAAA',
  '.....DAAWWWWWWWW',
  '.....DAAWWWWWWWW',
  '......DAAAAAAAAA',
  'DDD....DAAAAAAAA',
  'DBBD...DAAAAAAAA',
  'DBBBD..DAAAAAAAA',
  'DBBBBD.DAAAAAAAA',
  'DBBBBBDDAAAAAAAA',
  'DBBBBBBDAAAAAAAA',
  '.DBBBBBDAAAAAAAA',
  '..DBBBBDAAAAAAAA',
  '...DBBBDAAAAAAAA',
  '....DBBDAAAAAAAA',
  '.....DDDAAAAAAAA',
  '.......DAAAAAAAA',
  '.......DAADAAAAA',
  '.......DAAD.....',
  '.......DAAD.....',
  '......DDDDD.....',
  '................',
])

const B_KRAKEN = sym([
  '................',
  '...............D',
  '..............DA',
  '.............DAA',
  '............DAAA',
  '...........DAAAA',
  '..........DAAAAA',
  '.........DAAAAAA',
  '........DAAAAAAA',
  '.......DAAAAAAAA',
  '......DAAAAAAAAA',
  '.....DAAAAAAAAAA',
  '.....DAAEEEEAAAA',
  '.....DAEPPPPAAAA',
  '.....DAEPPPPAAAA',
  '.....DAAEEEEAAAA',
  '.....DAAAAAAAAAA',
  '.....DAAAAACCCCC',
  '.....DAAAAAAAAAA',
  '.....DDDDDDDDDDD',
  '..DBBD..DBBD..DB',
  '..DBBD..DBBD..DB',
  '.DBBD...DBBD..DB',
  '.DBBD...DBBD..DB',
  'DBBD....DBBD...D',
  'DBBD....DBBD....',
  'DBD.....DBD.....',
  '.DD......DD.....',
  '................',
  '................',
  '................',
  '................',
])

const B_OWL = sym([
  '................',
  '................',
  '....CC..........',
  '....CCC.........',
  '.....DCCDDDDDDDD',
  '.....DAAAAAAAAAA',
  '....DAAAAAAAAAAA',
  '...DAAAAAAAAAAAA',
  '...DAAEEEEEAAAAA',
  '...DAEEEPPEEAAAA',
  '...DAEEEPPEEAAAA',
  '...DAAEEEEEAAAAA',
  '...DAAAAAAACCCCC',
  '...DAAAAAAAACCCC',
  '...DAAAAAAAAAAAA',
  '...DAABBBBBBBBBB',
  '...DAABBBBBBBBBB',
  '...DAAABBBBBBBBB',
  '....DAABBBBBBBBB',
  '....DAAABBBBBBBB',
  '.....DAAABBBBBBB',
  '......DAAAAAAAAA',
  '.......DDAAAAAAA',
  '.........DDDDDDD',
  '..........DCCD..',
  '..........DCCD..',
  '.........DDDDD..',
  '................',
  '................',
  '................',
  '................',
  '................',
])

const B_GOLEM = sym([
  '................',
  '................',
  '......DDDDDDDDDD',
  '......DAAAAAAAAA',
  '......DAEEEAAAAA',
  '......DAEPPAAAAA',
  '......DAEEEAAAAA',
  '......DAAAAAAAAA',
  '......DAACCCCCCC',
  '......DAAAAAAAAA',
  '......DDDDDDDDDD',
  '..DDDDDDDDDDDDDD',
  '..DAAADDAAAAAAAA',
  '..DAAADDAAAAAAAA',
  '..DAAADDAACCCCCC',
  '..DAAADDAACCCCCC',
  '..DAAADDAAAAAAAA',
  '..DAAADDAAAAAAAA',
  '..DAAADDAAAAAAAA',
  '..DDDDDDAAAAAAAA',
  '........DAAAAAAA',
  '........DAAAAAAA',
  '........DDDDDDDD',
  '.........DAAAD..',
  '.........DAAAD..',
  '.........DAAAD..',
  '........DDDDDD..',
  '................',
  '................',
  '................',
  '................',
  '................',
])

const B_SERPENT = sym([
  '................',
  '................',
  '..........DDDDDD',
  '.........DAAAAAA',
  '.........DAEEEAA',
  '.........DAEPPAA',
  '.........DAAAAAA',
  '.........DAAWWWW',
  '.....DDDDAAAAAAA',
  '...DDAAAAAAAAAAA',
  '..DAAAAAAAAAAAAA',
  '..DAABBBBBBBBBBB',
  '..DAABBBBBBBBBBB',
  '..DAAABBBBBBBBBB',
  '...DAAAAAAAAAAAA',
  '.....DDAAAAAAAAA',
  '........DDAAAAAA',
  '..........DAAAAA',
  '..........DAAAAA',
  '.........DAAAAAA',
  '......DDDDDDDDDD',
  '...DDBBBBBBBBBBB',
  '..DBBBBBBBBBBBBB',
  '..DBBBBDDDDDDDDD',
  '..DBBBBBBBBBBBBB',
  '...DDBBBBBBBBBBB',
  '.....DDDDDDDDDDD',
  '................',
  '................',
  '................',
  '................',
  '................',
])

const B_BEAST = sym([
  '................',
  '..DD............',
  '..DAD...........',
  '..DAAD..........',
  '..DAAAD.........',
  '..DAAAADDDDDDDDD',
  '..DAAAAAAAAAAAAA',
  '..DAAEEEEAAAAAAA',
  '..DAAEPPEAAAAAAA',
  '..DAAEEEEAAAAAAA',
  '..DAAAAAAAAAAAAA',
  '...DAAAAAAAABBBB',
  '....DAAAAAAABBBB',
  '.....DAAAAAABWWW',
  '.....DAAAAAAAAAA',
  '....DAAAAAAAAAAA',
  '...DBBBBBBBBBBBB',
  '..DBBBBBBBBBBBBB',
  '.DBBBBBBBBBBBBBB',
  '.DBBBBBBBBBBBBBB',
  '..DBBBBBBBBBBBBB',
  '..DAAAAAAAAAAAAA',
  '..DAAAAAAAAAAAAA',
  '..DAAAAAAAAAAAAA',
  '..DAADDDDAAAAAAA',
  '..DAAD..DAAAAAAA',
  '..DAAD..DAAAAAAA',
  '..DAAD..DAAAAAAA',
  '..DCCD..DCCAAAAA',
  '..DDDD..DDDDDDDD',
  '................',
  '................',
])

const B_WHALE: Art = [
  '................................',
  '................................',
  '..............CC................',
  '.............CCCC...............',
  '............CC..CC..............',
  '............C....C..............',
  '.......DDDDDDDDDDDDDDD..........',
  '.....DDAAAAAAAAAAAAAAADD........',
  '...DDAAAAAAAAAAAAAAAAAAADD......',
  '..DAAAAAAAAAAAAAAAAAAAAAAAD.....',
  '.DAAEEAAAAAAAAAAAAAAAAAAAAAD..DD',
  'DAAEPPAAAAAAAAAAAAAAAAAAAAAAD.DA',
  'DAAEEAAAAAAAAAAAAAAAAAAAAAAAADAA',
  'DAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
  'DAWWWWWWAAAAAAAAAAAAAAAAAAAAADAA',
  'DBBBBBBBBBBBBBBBBBBBBBBBBBBBD.DA',
  '.DBBBBBBBBBBBBBBBBBBBBBBBBBD..DD',
  '..DDBBBBBBBBBBBBBBBBBBBBBDD.....',
  '....DDBBBBBBBBBBBBBBBBBDD.......',
  '.......DDDDDDDDDDDDDDDD.........',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
  '................................',
]

// ---------------- かたちと 色の わりあて ----------------

const SMALL: Record<string, Art> = { slime: SLIME, bug: BUG, bat: BAT, beast: BEAST, ghost: GHOST, snake: SNAKE, robot: ROBOT, bird: BIRD, crab: CRAB, turtle: TURTLE, mage: MAGE, fish: FISH }
const BIG: Record<string, Art> = { dragon: B_DRAGON, king: B_KING, demon: B_DEMON, kraken: B_KRAKEN, owl: B_OWL, whale: B_WHALE, golem: B_GOLEM, serpent: B_SERPENT, beast: B_BEAST }

// 色セット（A=本体 B=かげ C=アクセント）。D・E・P・W は 共通。
const COLORS: Record<string, [string, string, string]> = {
  green: ['#5cc45a', '#3a8f3a', '#f2e04a'],
  blue: ['#4f8fe0', '#3160a8', '#a8e8ff'],
  red: ['#e05a4a', '#a83428', '#ffd24a'],
  purple: ['#9a6ad0', '#6a44a0', '#e8c0ff'],
  gray: ['#9aa0aa', '#6a707a', '#d8dee8'],
  brown: ['#b07a44', '#7a5028', '#e8c88a'],
  yellow: ['#e8c44a', '#b08a24', '#fff0a8'],
  pink: ['#e88ab0', '#b05a80', '#ffd8e8'],
  cyan: ['#4fc4c4', '#2a8a8a', '#c0f8f8'],
  white: ['#e4e8f0', '#a8b0c0', '#7fc7e8'],
  dark: ['#5a5470', '#3a3550', '#c04a8a'],
  orange: ['#e8944a', '#b06024', '#ffd8a8'],
}

function palOf(c: string): Pal {
  const [A, B, C] = COLORS[c] ?? COLORS.green
  return { A, B, C, D: '#1a1424', E: '#ffffff', P: '#1a1424', W: '#ffffff' }
}

// 各ステージの ザコ／大ボスの 見た目
const LOOK: Record<string, { s: [string, string]; b: [string, string] }> = {
  'keisan-1': { s: ['bug', 'green'], b: ['dragon', 'green'] },
  'keisan-2': { s: ['bat', 'purple'], b: ['king', 'yellow'] },
  'keisan-3': { s: ['beast', 'gray'], b: ['demon', 'red'] },
  'keisan-4': { s: ['ghost', 'white'], b: ['king', 'dark'] },
  'keisan-5': { s: ['snake', 'green'], b: ['kraken', 'purple'] },
  'keisan-6': { s: ['robot', 'cyan'], b: ['dragon', 'purple'] },
  'ryou-1': { s: ['turtle', 'brown'], b: ['owl', 'brown'] },
  'ryou-2': { s: ['slime', 'green'], b: ['beast', 'green'] },
  'ryou-3': { s: ['beast', 'gray'], b: ['golem', 'gray'] },
  'ryou-4': { s: ['beast', 'brown'], b: ['golem', 'brown'] },
  'ryou-5': { s: ['turtle', 'green'], b: ['whale', 'blue'] },
  'ryou-6': { s: ['beast', 'yellow'], b: ['owl', 'orange'] },
  'zukei-1': { s: ['robot', 'orange'], b: ['golem', 'gray'] },
  'zukei-2': { s: ['robot', 'yellow'], b: ['dragon', 'green'] },
  'zukei-3': { s: ['slime', 'blue'], b: ['kraken', 'red'] },
  'zukei-4': { s: ['crab', 'purple'], b: ['serpent', 'green'] },
  'zukei-5': { s: ['crab', 'red'], b: ['kraken', 'orange'] },
  'zukei-6': { s: ['ghost', 'cyan'], b: ['dragon', 'blue'] },
  'kankei-1': { s: ['beast', 'brown'], b: ['beast', 'orange'] },
  'kankei-2': { s: ['bug', 'yellow'], b: ['crab', 'dark'] },
  'kankei-3': { s: ['bird', 'green'], b: ['owl', 'blue'] },
  'kankei-4': { s: ['snake', 'yellow'], b: ['dragon', 'red'] },
  'kankei-5': { s: ['mage', 'blue'], b: ['king', 'purple'] },
  'kankei-6': { s: ['fish', 'cyan'], b: ['demon', 'purple'] },
}

const FALLBACK = { s: ['slime', 'green'] as [string, string], b: ['dragon', 'red'] as [string, string] }

export function monsterArt(stageId: string, boss: boolean): { art: Art; pal: Pal; key: string } {
  const look = LOOK[stageId] ?? FALLBACK
  const [shape, color] = boss ? look.b : look.s
  const art = (boss ? BIG[shape] : SMALL[shape]) ?? SLIME
  return { art, pal: palOf(color), key: `${boss ? 'b' : 's'}:${shape}:${color}` }
}

// ドット絵の 大きさ（ザコ24ドット／大ボス32ドット）
export const monsterDots = (boss: boolean) => (boss ? 32 : 24)

// スプライト用の 画像URL（scale で 1ドットの ピクセル数を きめる。
// にじませない ために かならず 整数倍で 表示すること）
export function monsterUrl(stageId: string, boss: boolean, scale = 2): string {
  const { art, pal, key } = monsterArt(stageId, boss)
  return artUrl(`mon:${key}:${scale}`, art, pal, scale)
}

// ぜんぶの絵が 正方形（行数＝よこ幅）か たしかめる（テスト用）
export function allMonsterArts(): Record<string, Art> {
  return { ...Object.fromEntries(Object.entries(SMALL).map(([k, v]) => [`s:${k}`, v])), ...Object.fromEntries(Object.entries(BIG).map(([k, v]) => [`b:${k}`, v])) }
}
